name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps
      - name: Unit tests
        run: pytest -q tests/unit
      - name: Start app for E2E (port 8001)
        run: |
          nohup uvicorn app.main:app --host 127.0.0.1 --port 8001 &
          for i in {1..20}; do curl -sSf http://127.0.0.1:8001/login && break; sleep 1; done
      - name: E2E tests
        env: { BASE_URL: http://127.0.0.1:8001 }
        run: pytest -q tests/e2e

  docker:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # jaysocodi
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: jaysocodi/calc-app:latest
